[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=()"
    Cache-Control = "public, max-age=31536000, must-revalidate"
    Content-Security-Policy = """
      default-src 'self';
      base-uri 'self';
      form-action 'self';
      script-src 'self' 'sha384-xUYr75T+QT8UYrpPWrZk5+pt6KJsUrjRnBZhTeIZz8K7WwIPF9l7duqoZCw7bWhJ' https://www.googletagmanager.com https://www.google-analytics.com https://www.gstatic.com https://apis.google.com;
      script-src-elem 'self' https://www.googletagmanager.com https://www.google-analytics.com https://www.gstatic.com https://apis.google.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      style-src-elem 'self' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      img-src 'self' data: https://*.google-analytics.com https://*.google.com;
      connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://*.firestore.googleapis.com https://*.google-analytics.com;
      font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;
      frame-src 'self' https://www.google.com;
      object-src 'none';
      upgrade-insecure-requests;
    """

[functions]
  directory = "netlify/functions"