[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=()"
    Cache-Control = "no-store"
    Content-Security-Policy = """
      default-src 'self' unahrate.netlify.app;
      script-src 'self' https://www.gstatic.com https://apis.google.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      img-src 'self' data: https:;
      connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://*.firestore.googleapis.com;
      font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;
      frame-src 'none';
      base-uri 'self';
      form-action 'self';
    """

[functions]
  directory = "netlify/functions"